# ============================================
# RESTORAN BUYURTMA TIZIMI — KONFIGURATSIYA
# ============================================

# Server
server.port=8080
server.tomcat.timezone=Asia/Tashkent
spring.jackson.time-zone=Asia/Tashkent

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:restaurantdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=postgres
spring.datasource.password=123
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

# JWT Configuration
app.jwt.secret=UzbekistanRestoranFoodDeliverySecretKeyJWT2024VeryLongAndSecure256Bits!
app.jwt.expiration=86400000

# Logging
logging.level.com.restoran=INFO
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=WARN

# Jackson
spring.jackson.serialization.fail-on-empty-beans=false

# Telegram Bot Configuration
telegram.bot.token=8988031463:AAHTgeEO9Bg1p6z3bYfy-GYrYmoJ0zFRCRo
telegram.webapp.url=https://f73ad831080a5778-213-230-93-113.serveousercontent.com
